services:
  app1: &app
    build: .
    hostname: backend-1
    container_name: backend-1
    ports:
      - "9000:80"
    networks:
      - backend
      - payment-processor

    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "100M"
    
    depends_on:
      - redis
    
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_ADDR=redis:6379
      - APP_PORT=80

  app2:
    <<: *app
    hostname: backend-2
    container_name: backend-2
    ports:
      - "9001:80"
  
  proxy:
    image: nginx:latest
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30M"
  
  redis:
    image: redis:8-alpine
    container_name: rinha-redis
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "120M"
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true